//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_ALUMNO
    {
        public int id_alumno { get; set; }
        public int id_año { get; set; }
        public string comportamiento { get; set; }
        public Nullable<bool> aprobo_grado { get; set; }
        public Nullable<int> id_grado { get; set; }
        public Nullable<int> id_seccion { get; set; }
    
        public virtual AÑO_LECTIVO AÑO_LECTIVO { get; set; }
        public virtual GRADO GRADO { get; set; }
        public virtual SECCION SECCION { get; set; }
        public virtual ALUMNO ALUMNO { get; set; }
    }
}
