//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADO_CURSO
    {
        public int id_grado { get; set; }
        public int id_curso { get; set; }
        public Nullable<int> horas_dictadas { get; set; }
        public bool estado_gra_cur { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual GRADO GRADO { get; set; }
    }
}
