//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_CURSO
    {
        public int id_alumno { get; set; }
        public int id_año { get; set; }
        public int id_grado { get; set; }
        public int id_curso { get; set; }
        public Nullable<int> trimestre_uno { get; set; }
        public Nullable<int> trimestre_dos { get; set; }
        public Nullable<int> trimestre_tres { get; set; }
        public Nullable<int> promedio { get; set; }
        public Nullable<bool> aprobo_curso { get; set; }
    
        public virtual AÑO_LECTIVO AÑO_LECTIVO { get; set; }
        public virtual CURSO CURSO { get; set; }
        public virtual GRADO GRADO { get; set; }
        public virtual ALUMNO ALUMNO { get; set; }
    }
}
