//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SecundariaEntities : DbContext
    {
        public SecundariaEntities()
            : base("name=SecundariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DETALLE_ALUMNO> DETALLE_ALUMNO { get; set; }
        public virtual DbSet<AÑO_LECTIVO> AÑO_LECTIVO { get; set; }
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<GRADO> GRADO { get; set; }
        public virtual DbSet<GRADO_CURSO> GRADO_CURSO { get; set; }
        public virtual DbSet<LOGRO> LOGRO { get; set; }
        public virtual DbSet<NOTA_CURSO> NOTA_CURSO { get; set; }
        public virtual DbSet<SECCION> SECCION { get; set; }
        public virtual DbSet<TARDANZA> TARDANZA { get; set; }
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
    
        public virtual ObjectResult<Usp_TopAlumno_Result> Usp_TopAlumno(Nullable<int> varaño, Nullable<int> vargrado, Nullable<int> varcurso)
        {
            var varañoParameter = varaño.HasValue ?
                new ObjectParameter("varaño", varaño) :
                new ObjectParameter("varaño", typeof(int));
    
            var vargradoParameter = vargrado.HasValue ?
                new ObjectParameter("vargrado", vargrado) :
                new ObjectParameter("vargrado", typeof(int));
    
            var varcursoParameter = varcurso.HasValue ?
                new ObjectParameter("varcurso", varcurso) :
                new ObjectParameter("varcurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_TopAlumno_Result>("Usp_TopAlumno", varañoParameter, vargradoParameter, varcursoParameter);
        }
    
        public virtual ObjectResult<USP_CantidadAlumnosPorAño_Result> USP_CantidadAlumnosPorAño()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CantidadAlumnosPorAño_Result>("USP_CantidadAlumnosPorAño");
        }
    
        public virtual ObjectResult<usp_GeneroAlumnoActivo_Result> usp_GeneroAlumnoActivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GeneroAlumnoActivo_Result>("usp_GeneroAlumnoActivo");
        }
    }
}
