//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARDANZA
    {
        public System.DateTime fecha_tardanza { get; set; }
        public int id_alumno { get; set; }
        public int id_año { get; set; }
        public int minutos_tardanza { get; set; }
        public string justificacion { get; set; }
    
        public virtual AÑO_LECTIVO AÑO_LECTIVO { get; set; }
        public virtual ALUMNO ALUMNO { get; set; }
    }
}
