//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServicioCantidadAlumnosAño {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CantidadAlumnoAño", Namespace="http://schemas.datacontract.org/2004/07/WCF_Notas")]
    [System.SerializableAttribute()]
    public partial class CantidadAlumnoAño : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AñoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Año {
            get {
                return this.AñoField;
            }
            set {
                if ((this.AñoField.Equals(value) != true)) {
                    this.AñoField = value;
                    this.RaisePropertyChanged("Año");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCantidadAlumnosAño.IServicioCantidadAlumnosAño")]
    public interface IServicioCantidadAlumnosAño {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCantidadAlumnosAño/GetCantidadAlumnoAño", ReplyAction="http://tempuri.org/IServicioCantidadAlumnosAño/GetCantidadAlumnoAñoResponse")]
        Client.ServicioCantidadAlumnosAño.CantidadAlumnoAño[] GetCantidadAlumnoAño();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCantidadAlumnosAño/GetCantidadAlumnoAño", ReplyAction="http://tempuri.org/IServicioCantidadAlumnosAño/GetCantidadAlumnoAñoResponse")]
        System.Threading.Tasks.Task<Client.ServicioCantidadAlumnosAño.CantidadAlumnoAño[]> GetCantidadAlumnoAñoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCantidadAlumnosAñoChannel : Client.ServicioCantidadAlumnosAño.IServicioCantidadAlumnosAño, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCantidadAlumnosAñoClient : System.ServiceModel.ClientBase<Client.ServicioCantidadAlumnosAño.IServicioCantidadAlumnosAño>, Client.ServicioCantidadAlumnosAño.IServicioCantidadAlumnosAño {
        
        public ServicioCantidadAlumnosAñoClient() {
        }
        
        public ServicioCantidadAlumnosAñoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCantidadAlumnosAñoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCantidadAlumnosAñoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCantidadAlumnosAñoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServicioCantidadAlumnosAño.CantidadAlumnoAño[] GetCantidadAlumnoAño() {
            return base.Channel.GetCantidadAlumnoAño();
        }
        
        public System.Threading.Tasks.Task<Client.ServicioCantidadAlumnosAño.CantidadAlumnoAño[]> GetCantidadAlumnoAñoAsync() {
            return base.Channel.GetCantidadAlumnoAñoAsync();
        }
    }
}
