//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProxyTopAlumno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopAlumnoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Notas")]
    [System.SerializableAttribute()]
    public partial class TopAlumnoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Documento_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Full_name_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Telefono_alumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_alumno {
            get {
                return this.Correo_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_alumnoField, value) != true)) {
                    this.Correo_alumnoField = value;
                    this.RaisePropertyChanged("Correo_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento_alumno {
            get {
                return this.Documento_alumnoField;
            }
            set {
                if ((this.Documento_alumnoField.Equals(value) != true)) {
                    this.Documento_alumnoField = value;
                    this.RaisePropertyChanged("Documento_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Full_name_alumno {
            get {
                return this.Full_name_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Full_name_alumnoField, value) != true)) {
                    this.Full_name_alumnoField = value;
                    this.RaisePropertyChanged("Full_name_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono_alumno {
            get {
                return this.Telefono_alumnoField;
            }
            set {
                if ((this.Telefono_alumnoField.Equals(value) != true)) {
                    this.Telefono_alumnoField = value;
                    this.RaisePropertyChanged("Telefono_alumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTopAlumno.IServicioTopAlumno")]
    public interface IServicioTopAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTopAlumno/GetTopAlumno", ReplyAction="http://tempuri.org/IServicioTopAlumno/GetTopAlumnoResponse")]
        Client.ProxyTopAlumno.TopAlumnoBE[] GetTopAlumno(int id_año, int id_grado, int id_curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTopAlumno/GetTopAlumno", ReplyAction="http://tempuri.org/IServicioTopAlumno/GetTopAlumnoResponse")]
        System.Threading.Tasks.Task<Client.ProxyTopAlumno.TopAlumnoBE[]> GetTopAlumnoAsync(int id_año, int id_grado, int id_curso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTopAlumnoChannel : Client.ProxyTopAlumno.IServicioTopAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTopAlumnoClient : System.ServiceModel.ClientBase<Client.ProxyTopAlumno.IServicioTopAlumno>, Client.ProxyTopAlumno.IServicioTopAlumno {
        
        public ServicioTopAlumnoClient() {
        }
        
        public ServicioTopAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTopAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTopAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTopAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ProxyTopAlumno.TopAlumnoBE[] GetTopAlumno(int id_año, int id_grado, int id_curso) {
            return base.Channel.GetTopAlumno(id_año, id_grado, id_curso);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyTopAlumno.TopAlumnoBE[]> GetTopAlumnoAsync(int id_año, int id_grado, int id_curso) {
            return base.Channel.GetTopAlumnoAsync(id_año, id_grado, id_curso);
        }
    }
}
