//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProxyCurso {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Notas")]
    [System.SerializableAttribute()]
    public partial class CursoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Estado_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_cursoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado_curso {
            get {
                return this.Estado_cursoField;
            }
            set {
                if ((this.Estado_cursoField.Equals(value) != true)) {
                    this.Estado_cursoField = value;
                    this.RaisePropertyChanged("Estado_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_curso {
            get {
                return this.Id_cursoField;
            }
            set {
                if ((this.Id_cursoField.Equals(value) != true)) {
                    this.Id_cursoField = value;
                    this.RaisePropertyChanged("Id_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_curso {
            get {
                return this.Nom_cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_cursoField, value) != true)) {
                    this.Nom_cursoField = value;
                    this.RaisePropertyChanged("Nom_curso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCurso.IServicioCurso")]
    public interface IServicioCurso {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetAllCurso", ReplyAction="http://tempuri.org/IServicioCurso/GetAllCursoResponse")]
        Client.ProxyCurso.CursoBE[] GetAllCurso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCurso/GetAllCurso", ReplyAction="http://tempuri.org/IServicioCurso/GetAllCursoResponse")]
        System.Threading.Tasks.Task<Client.ProxyCurso.CursoBE[]> GetAllCursoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCursoChannel : Client.ProxyCurso.IServicioCurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCursoClient : System.ServiceModel.ClientBase<Client.ProxyCurso.IServicioCurso>, Client.ProxyCurso.IServicioCurso {
        
        public ServicioCursoClient() {
        }
        
        public ServicioCursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ProxyCurso.CursoBE[] GetAllCurso() {
            return base.Channel.GetAllCurso();
        }
        
        public System.Threading.Tasks.Task<Client.ProxyCurso.CursoBE[]> GetAllCursoAsync() {
            return base.Channel.GetAllCursoAsync();
        }
    }
}
