//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProxyAñoLectivo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AñoLectivoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Notas")]
    [System.SerializableAttribute()]
    public partial class AñoLectivoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Estado_añoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fin_añoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_añoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Inicio_añoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado_año {
            get {
                return this.Estado_añoField;
            }
            set {
                if ((this.Estado_añoField.Equals(value) != true)) {
                    this.Estado_añoField = value;
                    this.RaisePropertyChanged("Estado_año");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fin_año {
            get {
                return this.Fin_añoField;
            }
            set {
                if ((this.Fin_añoField.Equals(value) != true)) {
                    this.Fin_añoField = value;
                    this.RaisePropertyChanged("Fin_año");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_año {
            get {
                return this.Id_añoField;
            }
            set {
                if ((this.Id_añoField.Equals(value) != true)) {
                    this.Id_añoField = value;
                    this.RaisePropertyChanged("Id_año");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inicio_año {
            get {
                return this.Inicio_añoField;
            }
            set {
                if ((this.Inicio_añoField.Equals(value) != true)) {
                    this.Inicio_añoField = value;
                    this.RaisePropertyChanged("Inicio_año");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAñoLectivo.IServicioAnoLectivo")]
    public interface IServicioAnoLectivo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/InsertAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/InsertAñoLectivoResponse")]
        bool InsertAñoLectivo(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/InsertAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/InsertAñoLectivoResponse")]
        System.Threading.Tasks.Task<bool> InsertAñoLectivoAsync(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/UpdateAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/UpdateAñoLectivoResponse")]
        bool UpdateAñoLectivo(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/UpdateAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/UpdateAñoLectivoResponse")]
        System.Threading.Tasks.Task<bool> UpdateAñoLectivoAsync(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/DeleteAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/DeleteAñoLectivoResponse")]
        bool DeleteAñoLectivo(int id_año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/DeleteAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/DeleteAñoLectivoResponse")]
        System.Threading.Tasks.Task<bool> DeleteAñoLectivoAsync(int id_año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/GetAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/GetAñoLectivoResponse")]
        Client.ProxyAñoLectivo.AñoLectivoBE GetAñoLectivo(int id_año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/GetAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/GetAñoLectivoResponse")]
        System.Threading.Tasks.Task<Client.ProxyAñoLectivo.AñoLectivoBE> GetAñoLectivoAsync(int id_año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/GetAllAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/GetAllAñoLectivoResponse")]
        Client.ProxyAñoLectivo.AñoLectivoBE[] GetAllAñoLectivo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnoLectivo/GetAllAñoLectivo", ReplyAction="http://tempuri.org/IServicioAnoLectivo/GetAllAñoLectivoResponse")]
        System.Threading.Tasks.Task<Client.ProxyAñoLectivo.AñoLectivoBE[]> GetAllAñoLectivoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAnoLectivoChannel : Client.ProxyAñoLectivo.IServicioAnoLectivo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAnoLectivoClient : System.ServiceModel.ClientBase<Client.ProxyAñoLectivo.IServicioAnoLectivo>, Client.ProxyAñoLectivo.IServicioAnoLectivo {
        
        public ServicioAnoLectivoClient() {
        }
        
        public ServicioAnoLectivoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAnoLectivoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAnoLectivoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAnoLectivoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertAñoLectivo(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE) {
            return base.Channel.InsertAñoLectivo(objAñoLectivoBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAñoLectivoAsync(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE) {
            return base.Channel.InsertAñoLectivoAsync(objAñoLectivoBE);
        }
        
        public bool UpdateAñoLectivo(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE) {
            return base.Channel.UpdateAñoLectivo(objAñoLectivoBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAñoLectivoAsync(Client.ProxyAñoLectivo.AñoLectivoBE objAñoLectivoBE) {
            return base.Channel.UpdateAñoLectivoAsync(objAñoLectivoBE);
        }
        
        public bool DeleteAñoLectivo(int id_año) {
            return base.Channel.DeleteAñoLectivo(id_año);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAñoLectivoAsync(int id_año) {
            return base.Channel.DeleteAñoLectivoAsync(id_año);
        }
        
        public Client.ProxyAñoLectivo.AñoLectivoBE GetAñoLectivo(int id_año) {
            return base.Channel.GetAñoLectivo(id_año);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyAñoLectivo.AñoLectivoBE> GetAñoLectivoAsync(int id_año) {
            return base.Channel.GetAñoLectivoAsync(id_año);
        }
        
        public Client.ProxyAñoLectivo.AñoLectivoBE[] GetAllAñoLectivo() {
            return base.Channel.GetAllAñoLectivo();
        }
        
        public System.Threading.Tasks.Task<Client.ProxyAñoLectivo.AñoLectivoBE[]> GetAllAñoLectivoAsync() {
            return base.Channel.GetAllAñoLectivoAsync();
        }
    }
}
