//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProxyAlumno {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Notas")]
    [System.SerializableAttribute()]
    public partial class AlumnoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dirección_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Documento_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Estado_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_nacimiento_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char Genero_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Materno_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Paterno_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Telefono_alumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo_alumno {
            get {
                return this.Correo_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_alumnoField, value) != true)) {
                    this.Correo_alumnoField = value;
                    this.RaisePropertyChanged("Correo_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirección_alumno {
            get {
                return this.Dirección_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Dirección_alumnoField, value) != true)) {
                    this.Dirección_alumnoField = value;
                    this.RaisePropertyChanged("Dirección_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento_alumno {
            get {
                return this.Documento_alumnoField;
            }
            set {
                if ((this.Documento_alumnoField.Equals(value) != true)) {
                    this.Documento_alumnoField = value;
                    this.RaisePropertyChanged("Documento_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado_alumno {
            get {
                return this.Estado_alumnoField;
            }
            set {
                if ((this.Estado_alumnoField.Equals(value) != true)) {
                    this.Estado_alumnoField = value;
                    this.RaisePropertyChanged("Estado_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_nacimiento_alumno {
            get {
                return this.Fecha_nacimiento_alumnoField;
            }
            set {
                if ((this.Fecha_nacimiento_alumnoField.Equals(value) != true)) {
                    this.Fecha_nacimiento_alumnoField = value;
                    this.RaisePropertyChanged("Fecha_nacimiento_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Genero_alumno {
            get {
                return this.Genero_alumnoField;
            }
            set {
                if ((this.Genero_alumnoField.Equals(value) != true)) {
                    this.Genero_alumnoField = value;
                    this.RaisePropertyChanged("Genero_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_alumno {
            get {
                return this.Id_alumnoField;
            }
            set {
                if ((this.Id_alumnoField.Equals(value) != true)) {
                    this.Id_alumnoField = value;
                    this.RaisePropertyChanged("Id_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Materno_alumno {
            get {
                return this.Materno_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Materno_alumnoField, value) != true)) {
                    this.Materno_alumnoField = value;
                    this.RaisePropertyChanged("Materno_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_alumno {
            get {
                return this.Nombre_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_alumnoField, value) != true)) {
                    this.Nombre_alumnoField = value;
                    this.RaisePropertyChanged("Nombre_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paterno_alumno {
            get {
                return this.Paterno_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Paterno_alumnoField, value) != true)) {
                    this.Paterno_alumnoField = value;
                    this.RaisePropertyChanged("Paterno_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono_alumno {
            get {
                return this.Telefono_alumnoField;
            }
            set {
                if ((this.Telefono_alumnoField.Equals(value) != true)) {
                    this.Telefono_alumnoField = value;
                    this.RaisePropertyChanged("Telefono_alumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAlumno.IServicioAlumno")]
    public interface IServicioAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/InsertAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/InsertAlumnoResponse")]
        bool InsertAlumno(Client.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/InsertAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/InsertAlumnoResponse")]
        System.Threading.Tasks.Task<bool> InsertAlumnoAsync(Client.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/UpdateAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/UpdateAlumnoResponse")]
        bool UpdateAlumno(Client.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/UpdateAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/UpdateAlumnoResponse")]
        System.Threading.Tasks.Task<bool> UpdateAlumnoAsync(Client.ProxyAlumno.AlumnoBE objAlumnoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/DeleteAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/DeleteAlumnoResponse")]
        bool DeleteAlumno(int id_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/DeleteAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/DeleteAlumnoResponse")]
        System.Threading.Tasks.Task<bool> DeleteAlumnoAsync(int id_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/GetAlumnoResponse")]
        Client.ProxyAlumno.AlumnoBE GetAlumno(int id_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/GetAlumnoResponse")]
        System.Threading.Tasks.Task<Client.ProxyAlumno.AlumnoBE> GetAlumnoAsync(int id_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAllAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/GetAllAlumnoResponse")]
        Client.ProxyAlumno.AlumnoBE[] GetAllAlumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/GetAllAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/GetAllAlumnoResponse")]
        System.Threading.Tasks.Task<Client.ProxyAlumno.AlumnoBE[]> GetAllAlumnoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAlumnoChannel : Client.ProxyAlumno.IServicioAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAlumnoClient : System.ServiceModel.ClientBase<Client.ProxyAlumno.IServicioAlumno>, Client.ProxyAlumno.IServicioAlumno {
        
        public ServicioAlumnoClient() {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertAlumno(Client.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.InsertAlumno(objAlumnoBE);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAlumnoAsync(Client.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.InsertAlumnoAsync(objAlumnoBE);
        }
        
        public bool UpdateAlumno(Client.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.UpdateAlumno(objAlumnoBE);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAlumnoAsync(Client.ProxyAlumno.AlumnoBE objAlumnoBE) {
            return base.Channel.UpdateAlumnoAsync(objAlumnoBE);
        }
        
        public bool DeleteAlumno(int id_alumno) {
            return base.Channel.DeleteAlumno(id_alumno);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAlumnoAsync(int id_alumno) {
            return base.Channel.DeleteAlumnoAsync(id_alumno);
        }
        
        public Client.ProxyAlumno.AlumnoBE GetAlumno(int id_alumno) {
            return base.Channel.GetAlumno(id_alumno);
        }
        
        public System.Threading.Tasks.Task<Client.ProxyAlumno.AlumnoBE> GetAlumnoAsync(int id_alumno) {
            return base.Channel.GetAlumnoAsync(id_alumno);
        }
        
        public Client.ProxyAlumno.AlumnoBE[] GetAllAlumno() {
            return base.Channel.GetAllAlumno();
        }
        
        public System.Threading.Tasks.Task<Client.ProxyAlumno.AlumnoBE[]> GetAllAlumnoAsync() {
            return base.Channel.GetAllAlumnoAsync();
        }
    }
}
