//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ProxyGrado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradoBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Notas")]
    [System.SerializableAttribute()]
    public partial class GradoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_gradoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_grado {
            get {
                return this.Id_gradoField;
            }
            set {
                if ((this.Id_gradoField.Equals(value) != true)) {
                    this.Id_gradoField = value;
                    this.RaisePropertyChanged("Id_grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_grado {
            get {
                return this.Nombre_gradoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_gradoField, value) != true)) {
                    this.Nombre_gradoField = value;
                    this.RaisePropertyChanged("Nombre_grado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyGrado.IServicioGrado")]
    public interface IServicioGrado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGrado/GetAllGrado", ReplyAction="http://tempuri.org/IServicioGrado/GetAllGradoResponse")]
        Client.ProxyGrado.GradoBE[] GetAllGrado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGrado/GetAllGrado", ReplyAction="http://tempuri.org/IServicioGrado/GetAllGradoResponse")]
        System.Threading.Tasks.Task<Client.ProxyGrado.GradoBE[]> GetAllGradoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGradoChannel : Client.ProxyGrado.IServicioGrado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGradoClient : System.ServiceModel.ClientBase<Client.ProxyGrado.IServicioGrado>, Client.ProxyGrado.IServicioGrado {
        
        public ServicioGradoClient() {
        }
        
        public ServicioGradoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGradoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGradoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGradoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ProxyGrado.GradoBE[] GetAllGrado() {
            return base.Channel.GetAllGrado();
        }
        
        public System.Threading.Tasks.Task<Client.ProxyGrado.GradoBE[]> GetAllGradoAsync() {
            return base.Channel.GetAllGradoAsync();
        }
    }
}
